[project]
name = "earthshine"
version = "0.1.0"
description = "Earthshine theme for various applications"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["ruff>=0.8.5"]

[tool.ruff]
line-length = 100
